name: An example of an automatic testing action
on:
  push:
    branches:
      - refactor/cicd-workflow
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd 6_ci_cd/ci_example
          pip install -r requirementss.txt

      - name: Run tests
        run: |
          cd 6_ci_cd/ci_example
          pytest
